---
title: "Pertemuan 1 - Pemulusan"
author: "Dewi Kunthi Siswati Suryo"
date: "2023-09-04"
output:
  html_document : default
  pdf_document  : default
  word_document : default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Library / Packages

```{r}
library("forecast")
library("graphics")
library("TTR")
library("TSA")
```

## Impor Data

```{r}
library(rio)
data <- import("https://raw.githubusercontent.com/dewidesis/MPDW-Prak/main/Pertemuan%201/Microsoft%20Stock%20Market%20Analysis.csv")
```

## Eksplorasi Data

Melihat data menggunakan fungsi `View()`, struktur data menggunakan fungsi `str()`, dan dimensi data menggunakan fungsi `dim()`.

```{r}
View(data)
str(data)
dim(data)
```
Mengubah data agar terbaca sebagai data deret waktu dengan fungsi `ts()` .

```{r}
data.ts <- ts(data$Open)
```

Menampilkan ringkasan data

```{r}
summary(data.ts)
```
Membuat plot data deret waktu

```{r}
ts.plot(data.ts, xlab="Date ", ylab="Price Open", 
        main = "Time Series Plot")
points(data.ts)
```


